### ISSUE TITLE
v1.4.0 Roadmap 

### ISSUE THREAD

**Issue by YegorZaremba** [nsfw-filter/nsfw-filter#144]
### Roadmap

- [x] Create roadmap
- [ ] Improve docs:
   - [ ] Update activity diagram #152 
   - [ ] Add DOM `attributes` statuses #117
- [ ] Filter raw image data #148 
- [ ] Allow users to download different ML models in the popup window #149 
- [ ] Preserve site layout until processes complete #151 
- [ ] DOM Nodes and JS listeners drops #139 
- [ ] Add badge of blocked images #78 
- [ ] Handle error in loading queue while tab url is changed #138 
- [ ] Add more unit and e2e tests (?)
- [ ] Reduce popup window js bundle size in production #154 
- [x] Filter strictness doesn't appear to work on edge #153

### Release date: TBA

**Comment by YegorZaremba** [comment]
Its better to close it =)
