### ISSUE TITLE
v1.3.0 Roadmap

### ISSUE THREAD

**Issue by YegorZaremba** [nsfw-filter/nsfw-filter#90]
## v1.3.0 Roadmap

**nsfw-filter**
- [x] Create roadmap
- [x] Add a few e2e test-cases
- [x] Add popup #79 
- [x] Refactor lazy loading #73 
- [x] Add cache #38 
- [x] Add strictness bar #58 
- [x] Setup auto-updating:
    - [x] Chrome #72 
    - [x] Firefox #69 
- [x] Update nsfwjs model #80 
- [x] Fix all image bugs:
    - [x] `<img>`
    - ~~gif~~
    - ~~webp~~
    - ~~svg~~
    - ~~canvas~~
    - ~~picture~~ (?)
- [x] unit-tests:
    - ~~[ConcurrentQueue](https://github.com/nsfw-filter/nsfw-filter/blob/master/src/background/PredictionQueue/ConcurrentQueue.ts)~~
    - [x] [LRUCache](https://github.com/nsfw-filter/nsfw-filter/blob/master/src/background/Model/LRUCache.ts)
    - [x] [handleFilterStrictness](https://github.com/nsfw-filter/nsfw-filter/blob/master/src/background/Model/Model.ts#L116)

**nsfwjs**
- ~~Finish [gif improvements](https://github.com/infinitered/nsfwjs/pull/401)~~
- ~~Add a few e2e test-cases (?)~~

### Finish date: November 25

**UPD1** Not sure that we should filter gif images. Webpage sends gif url to background worker and after that it loads gif image, depends on size, but approx it takes 0.5-4 seconds(and ~50-70ms to filter) for 1 gif image. So I decided to remove gif filtering in v1.3.0

**Comment by YegorZaremba** [comment]
Hi @navendu-pottekkat, looks like we are ready for `v1.3.0` release

Related issues: #81, #82, #86 and #93

cc @govza

**Comment by navendu-pottekkat** [comment]
@YegorZaremba Yes, I will test it out. We will plan the release after some extensive testing for a couple of days. We should release by the end of the month right?

**Comment by YegorZaremba** [comment]
@navendu-pottekkat I would like to do it today/tmrw 'cause moderation of chrome webstore takes ~5 days

**Comment by navendu-pottekkat** [comment]
I am testing it out currently. I will submit the extension to Chrome today itself.

**Comment by YegorZaremba** [comment]
Nice to hear it, thanks
Could you pls say a couple words about filtering speed/performance, how does it work on your machine?
ps. don't forget about mozila webstore (just to remember)

**Comment by navendu-pottekkat** [comment]
@YegorZaremba One change: In the popup, the model should be MobileNet_v1.1 

Should we add links to our Patreon or Open Collective in the popup?

**Comment by YegorZaremba** [comment]
> should be MobileNet_v1.1

Get it, thanks

> Should we add links to our Patreon or Open Collective in the popup?

Don't think so, AdBlock doesn't have such kind of links. I don't think about it. Let's discuss about this in the future releases

**Comment by navendu-pottekkat** [comment]
@YegorZaremba It is working really fast, no issues there. One more suggestion, the show logs checkbox should be aligned to center or justified. I think it would look better, it is up to you. Rest looks really good. Awesome work!

**Comment by navendu-pottekkat** [comment]
> Don't think so, AdBlock doesn't have such kind of links. I don't think about it. Let's discuss in the future releases

Okay, then we will keep as it is

**Comment by YegorZaremba** [comment]
> It is working really fast, no issues there

😊😊😊 thanks

**Comment by YegorZaremba** [comment]
> should be MobileNet_v1.1

Done #145 

> One more suggestion, the show logs checkbox should be aligned to center or justified. I think it would look better, it is up to you

I plan to add more checkboxes(like beta gif filtering, beta video filtering) in the future. Length of their text is different. I decided to align them to the left

> Rest looks really good. Awesome work!

Thanks for feedback :blush:

**Comment by YegorZaremba** [comment]
@navendu-pottekkat Just published v1.3.0 release :rocket: 
https://github.com/nsfw-filter/nsfw-filter/releases/tag/v1.3.0

**Comment by navendu-pottekkat** [comment]
@YegorZaremba I am updating in the store

**Comment by navendu-pottekkat** [comment]
I have updated in Firefox store and I will test to make sure that it works and then we will submit to chrome store

**Comment by navendu-pottekkat** [comment]
@YegorZaremba the versions in both Chrome and Firefox are updated to 1.3 When should we start the promotion?

**Comment by YegorZaremba** [comment]
Wow, so fast for chrome webstore. Does it take only one day?

![Screenshot from 2020-10-27 09-56-50](https://user-images.githubusercontent.com/31797554/97267219-dc697280-183a-11eb-9005-2b5faa6aef47.png)

:rocket: :rocket: :rocket: 

Let's take several days for preparation and start on Friday and Saturday, what do yo think?

**Comment by YegorZaremba** [comment]
Done, closed
